### ISSUE TITLE
More protocols

### ISSUE THREAD

**Issue by markuszeller** [vschwaberow/rprobe#3]
Support more protocols by using a regex `|^(.*?)://|`.

**Comment by vschwaberow** [comment]
Needs more work as reqwest is meant for doing HTTP/HTTPS stuff. I will introduce filtering for any cases of other protocols in rprobe first.

**Comment by vschwaberow** [comment]
Continued effort

**Comment by vschwaberow** [comment]
Concentration on HTTP, HTTPS
